# Generated by Django 4.0.6 on 2022-08-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_by_blog',
            field=models.BooleanField(default=False),
        ),
    ]
