# Generated by Django 4.0.6 on 2022-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_edited_by_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.FileField(default=1, max_length=900, upload_to=None),
            preserve_default=False,
        ),
    ]
