# Generated by Django 4.0.6 on 2022-08-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
