# Generated by Django 4.0.6 on 2022-08-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_test_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_boolean',
        ),
    ]
